apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # "prometheus" resolves via Docker Compose service name
    url: http://prometheus:9090
    isDefault: true
    editable: true
